kind: Deployment
apiVersion: apps/v1
metadata: 
  name: testuser
spec:
  replicas: 2
  selector: # tells the controller which pods to watch / belong to
    matchLabels:
      app: testuser
  template:
    metadata:
      labels:
        app: testuser
    spec:
      containers:
        - name: testuser
          image: devvignesh/pipeline-job
          imagePullPolicy: Always
          ports:
            - containerPort: 80
