kind: Service                             
apiVersion: v1
metadata:
  name: testuser
  labels:
    app: testuser
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: testuser                    
  type: LoadBalancer                   